\input texinfo
@c %**start of header
@setfilename jed.info
@settitle Jed
@c %&&end of header

@include version.texi

@dircategory Multimedia Management
@direntry
* Jed: (jed).                  Jed
@end direntry

@copying
This is edition @value{EDITION},
last updated @value{UPDATED},
of @cite{The Jed Manual},
for @code{jed}, version @value{VERSION}.

Copyright @copyright{} 2024 Ben M. Sutter
@end copying

@titlepage
@title Jed
@subtitle There Ain't No Place I'd Rather Be!
@subtitle Edition @value{EDITION}
@subtitle @value{UPDATED-MONTH}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@node Top
@top
This is edition @value{EDITION},
last updated @value{UPDATED},
of @cite{The Jed Manual},
for @code{jed}, version @value{VERSION}.

@menu
* Introduction::     Goals and Constraints
* Index::            Complete index.
@end menu

@node Introduction
@chapter Introduction
@cindex introduction
This is filler text for the introduction.

@node What This Is
@section What This Is
First section of first chapter.

@node What This Isn't
@section What This Isn't.
Second section of first chapter.

@node Index
@unnumbered Index
@printindex cp

@bye
